[tool.poetry]
name = "open-myminecraftserver"
version = "0.1.0"
description = ""
authors = ["Skywind5487 <skywind5487@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
discord = "^2.3.2"
discord-py = "^2.4.0"
python-dotenv = "^1.0.1"
plyer = "^2.1.0"
pynacl = "^1.5.0"
psutil = "^6.1.1"
python-frontmatter = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
